name: Documentation

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3s
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install documentation-building requirements
        run: |
          set -vxeuo pipefail
          python -m pip install -r requirements-docs.txt
          python -m pip install . --no-deps

      - name: Build Docs
        run: make -C docs html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
